name: TEST - SPDX

on:
  push:

jobs:
  spdx-test:
    runs-on: ubuntu-latest
      - uses: actions/attest-sbom@v1
        with:
          subject-path: '.github/workflows/spdx.yaml'
          sbom-path: 'sbom.spdx.json'
